-   id: no_implicit_optional_checker
    name: no implicit optional checker
    description: A codemod to make your implicit optional type hints PEP 484 compliant.
    entry: no_implicit_optional
    language: python
    types: [python]