-   id: no_implicit_optional
    name: no_implicit_optional
    description: Upgrade the typing annotations syntax to PEP 585 and PEP 604.
    entry: no_implicit_optional
    language: python
    types: [python]